#PROCEDIMIENTO PARA CONECTARME A UNA BASE DE DATOS POR MEDIO DE LAN
SHOW VARIABLES LIKE "%net%"; --> VERIFICAR EN EL SHELL DE MYSQL
create user 'Maestro'@'%' IDENTIFIED BY 'lasurtidora123'; --> USUARIO Y CONTRASEÑA PARA ACCEDER
GRANT ALL PRIVILEGES ON *.* TO 'Maestro'@'%'; --> AGREGAMOS TODOS LOS PRIVILEGIOS
SELECT user, host FROM mysql.user; --> VERIFICAMOS

private $servername = "192.168.1.104"; --> DIRECCIÓN IP DE LA MÁQUINA MAESTRO
private $username = "Maestro"; --> NOMBRE DEL USUARIO CREADO EN LA MAQUINA MAESTRO
private $password = "lasurtidora123"; --> CONTRASEÑA DEL USUARIO
private $bd_name = "lasurtidoradelhogar";  --> BASE DE DATOS MAESTRO.

#OJO : NO SE TIENE QUE REPLICAR LA BASE DE DATOS.